brain-score/brain-score.web

benchmarks/migrations/0001_initial.py
benchmarks/models.py
benchmarks/templates/benchmarks/table.html
static/benchmarks/css/table.sass
static/benchmarks/fixture-benchmarks.json

show benchmark version when present

---

benchmarks/views/index.py
static/benchmarks/css/table.sass

color nonbrain benchmarks (e.g. ImageNet) in gray instead of red-green

---

README.md
benchmarks/fixtures/fixture-benchmarktypes.json
benchmarks/fixtures/fixture-models.json
benchmarks/fixtures/fixture-scores.json
benchmarks/fixtures/fixture-users.json
benchmarks/forms.py
benchmarks/models.py
benchmarks/templates/benchmarks/compare.html
benchmarks/templates/benchmarks/profile.html
benchmarks/templates/benchmarks/submissions.html
benchmarks/templates/benchmarks/table.html
benchmarks/tests/test_views.py
benchmarks/urls.py
benchmarks/views/index.py
benchmarks/views/user.py
package.json
setup.py
static/benchmarks/css/bulma.sass
static/benchmarks/js/compare.js
static/benchmarks/js/resubmit.js
static/benchmarks/js/table-expansion.js
web/settings.py

- Added versioning of benchmarks
- Added resubmission dialog
- Reworked submission dialog
- Add some additional test data
- Add a get_secret method, because it was not available (?)
- Add bulma extensions

Adjust website for new submission system - Franzi

---

static/benchmarks/js/table-expansion.js

run table expansion script on document ready

---

static/benchmarks/css/table.sass

remove box-shadow due to display issues, especially on Safari

---

benchmarks/views/user.py

see https://github.com/brain-score/jenkins/blob/ecf152199c4d9577ac87766c358b98f9ba907da0/check_file_new.py#L18 and https://github.com/brain-score/brain-score/blob/48582851a8fd114b1d88a0512de27d62fd57b57d/brainscore/submission/configuration.py#L57

fix key models->model_ids

---

benchmarks/views/index.py

update coloring to highlight differences between models, not benchmarks

---

benchmarks/views/user.py

need to test that new users are still created properly after merging

fix forms for password reset

---

benchmarks/templates/benchmarks/table.html
benchmarks/views/index.py
static/benchmarks/css/table.sass

show number of child benchmarks for parent benchmarks

---

benchmarks/views/user.py

before, failed submissions would be taken into account

fix submission restriction: include only successful submissions

---

benchmarks/views/index.py

resolve https://github.com/brain-score/brain-score.web/issues/33

show all rows to superuser; deal with rank edge-case

---

benchmarks/models.py
benchmarks/templates/benchmarks/profile.html
benchmarks/templates/benchmarks/table.html
benchmarks/urls.py
benchmarks/views/index.py
benchmarks/views/user.py
static/benchmarks/css/table.sass

resolve https://github.com/brain-score/brain-score.web/issues/61

display submitter instead of model author

---

benchmarks/views/user.py

Changed Jenkins to send email to user email instead of user name as before

---

benchmarks/views/index.py

This should fix the current 500 internal server error in the user profile, that came about as a result of incorrectly processing benchmark hierarchies with the new V1 benchmarks (https://github.com/brain-score/brain-score/pull/241)

process benchmarks deeper in the hierarchy first

---

benchmarks/views/index.py

such that, when all of a parent's children are nan, the parent will also be nan (rather than 0)

carry over childrens' nan score when computing parent average

---

benchmarks/templates/benchmarks/profile.html

Makes the save button work now, allows users to update their username

Save button fix

---

benchmarks/templates/benchmarks/base.html
benchmarks/templates/benchmarks/competition.html
static/benchmarks/css/competition.sass
static/benchmarks/css/header.sass
static/benchmarks/css/main.sass

color competition nav item green, rewording, format

---

benchmarks/templates/benchmarks/competition.html

add site navigation

---

benchmarks/templates/benchmarks/competition.html

update slack invitation, explain third party model submission
resolve #124 
resolve #123

Competition faq updates

---

benchmarks/views/index.py

count unscored benchmarks as 0 for averaging

---

benchmarks/templates/benchmarks/model.html
benchmarks/templates/benchmarks/table.html
benchmarks/views/index.py
static/CACHE/css/main.0d3eaaae676c.css

Hey,
I'd like to see the model names when I'm logged in so I created this pull request.
I'm not a django developer so I don't know if its safe (and memory efficient?) to pass the request object to the index page. 
But if you think it's ok, I guess it would make the leaderboard look nicer to user and superuser. 
I think the actual way to go would be to create a view for the table..
Also I'm not able to test this so probably there's a mistake somewhere?

passing request to index to display users model names

---

benchmarks/views/competition.py

make models public only if all user's grouped models are public

---

.travis.yml
benchmarks/templates/benchmarks/base.html

remove competition tab

---

benchmarks/models.py

following https://stackoverflow.com/a/70657013/2225200

fix ugettext_lazy -> gettext_lazy import

---

benchmarks/views/user.py

following https://stackoverflow.com/a/70389991/2225200

fix force_text -> force_str

---

Dockerfile

Site is currently down with 5xx errors. This was the fix was given by AWS themselves.

Add a docker prune command to get rid of unneeded objects. 

---

web/settings.py

Currently Environment is in SEVERE state due to failing requests from load balancer. AWS guy says this should fix it.

AWS suggested fix for IP subnet ALLOWED_HOSTS

---

benchmarks/templates/benchmarks/central_profile.html
benchmarks/templates/benchmarks/profile.html
benchmarks/templates/benchmarks/upload.html

Adding navbar and styling to views where it was missing.

Fix view styling

---

benchmarks/templates/benchmarks/compare.html
benchmarks/templates/benchmarks/components/left-sidebar.html
benchmarks/urls.py
benchmarks/views/compare.py
static/benchmarks/css/comparison.sass
static/benchmarks/js/compare.js

Adds a route for the compare component

add compare route and view

---

web/settings.py

AWS environments have been updated, and this PR adds them to allowed_hosts.

Add the updated environment URLs to site ALLOWED_HOSTS

---

benchmarks/templates/benchmarks/central_profile.html
benchmarks/templates/benchmarks/components/left-sidebar.html
benchmarks/templates/benchmarks/profile.html
benchmarks/templates/benchmarks/submissions.html
benchmarks/templates/benchmarks/tutorials/tutorial.html
benchmarks/views/user.py
static/benchmarks/css/tutorial.sass

Brings the profile page in line with the rest of the site for new UI

Update profile page

---

benchmarks/templates/benchmarks/tutorials/tutorial_troubleshooting.html

Adds the question and answer covering the error:
` assert len(logits['neuroid']) == 1000`
from the console log.

add logits error to troubleshooting

---

benchmarks/views/index.py

re-enable leaderboard caching

---

benchmarks/templates/benchmarks/competition2024.html

small improvements to the competition page: add critiques header; and models are now linked

competition2024 minor improvements: critiques header; link models

---

benchmarks/templates/benchmarks/landing_page.html

Per Jim's request to update the landing page text:
The Brain-Score platform aims to yield strong computational models of the brain and mind.
Changed to  —>
The Brain-Score platform aims to yield accurate, machine executable models of how the brain gives rise to the mind.
Democratizing the search for natural intelligence.
Changed to  —>
Democratizing the search for scientific models of natural intelligence.

Jim's suggested text fixes

---

benchmarks/templates/benchmarks/tutorials/tutorial_quickstart.html

As referenced in [here](https://github.com/brain-score/vision/issues/686)

add command to force the pip latest version

---

benchmarks/templates/benchmarks/release2_0.html
benchmarks/urls.py
benchmarks/views/release2_0.py

add 2.0 release page

---

benchmarks/templates/benchmarks/competition2024.html
static/benchmarks/css/competition.sass

specify competition prize pool

---

benchmarks/templates/benchmarks/tutorials/tutorial_quickstart.html

Adresses Issue brain-score/vision/#891 in vision

quick and minor quickstart edits

---

deployment.md

Adds the documentation about the order of operations surrounding website deployment and Github staging.

Add website staging information

---

README.md
deployment.md

This updates the Website README.md into 2.0 and adds multiple info sections.

Update website readme

---

deployment.md

Adds detailed documentation on: 
1. Elastic Beanstalk
2. AWS Help

Add updated docs for EB

---

benchmarks/views/user.py

This updates the resubmission job URL to be in line with 2.0 and will fix the 500 website error on resubmission

Fix resubmission 500 error

---

README.md

Covers extra information about the website not previously recorder: DNS, gmail account, etc

Add more website docs 

---

README.md

Add docs for a Django overview, specifically in regards to Brain-Score

Add django docs

---

benchmarks/templates/benchmarks/tutorials/models/quickstart.html

fixing detail

---

benchmarks/templates/benchmarks/landing_page.html

Just removed the banner entirely.

Competition Banner Update

---

README.md

Updates the instructions in the README for setting up and running the website locally.

Jimn2 update readme

---

benchmarks/templates/benchmarks/tutorials/models/quickstart.html

I noticed a small mistake in the quickstart.  This fixes it.

Fixing a detail in the quickstart

---

benchmarks/views/index.py

Fixes error where the csv download would throw a 500 on page load of a profile with no submissions.

fix 500 error on blank csv

---

benchmarks/templates/benchmarks/tutorials/models/deepdive_1.html

Kartik, when you and I talked, we discussed adding information about model summary tools to DD1.  This is my first cut at doing that.

Adding info on model summary tools to Deep Dive 1.

---

benchmarks/templates/benchmarks/tutorials/models/deepdive_1.html

Hey Kartik,
This fixes the font issues in the numbered list in part 9.  This should be all good now.

Fixed fonts in the numbered parts of part 9

---

benchmarks/templates/benchmarks/already_submitted.html
benchmarks/templates/benchmarks/profile.html
benchmarks/views/user.py

Currently, due to not supporting model versioning, plugin submissions are disabled.

Disable resubmissions

---

benchmarks/templates/benchmarks/inactive_account.html
benchmarks/views/user.py

Adds functionality to determine if a user is inactive. If so, route to dedicated page.

Password Reset Fix

---

benchmarks/templates/benchmarks/tutorials/models/deepdive_2.html
benchmarks/templates/benchmarks/tutorials/models/quickstart.html

My update to Deep Dive 2 that combines Deep Dives 2 and 3.  In the next sprint, this DD2 will become the new DD3 (I'll be adding a new DD1).
I also changed 3.8 to 3.11 and removed a misleading reference to CLI in the Quickstart.

Update to DD2 and 2 minor fixes on the Quickstart

---

web/settings.py

In my previous PR #357, a change to `settings.py` got included. Reverting that change.

Change database back to dev db

---

benchmarks/templates/benchmarks/tutorials/benchmarks/benchmarks.html
benchmarks/templates/benchmarks/tutorials/benchmarks/create_benchmark.html
benchmarks/templates/benchmarks/tutorials/benchmarks/package_data.html

Minor updates to the benchmark tutorials.

Updates to the benchmark tutorials.

---

benchmarks/templates/benchmarks/invalid_zip.html
benchmarks/templates/benchmarks/upload.html

Kartik,
These are the three mods you requested.  For the missing image, I removed reference to the image and included a link to the model tutorials (that imo give a more complete description of what to do with formatting issues than that image.)

Fixes to the website submissions page

---

web/settings.py

Adds the new Dev and Prod domain URLs to ALLOWED_HOSTS. This is due to us moving from previous DiCarlo EB to Quest EB. 
Ready to be merged

Add new eb domains

---

docs/source/modules/deployment.rst

Update the URLs and deployment names for new Brain-Score AWS (from DiCarlo AWS)

update docs for new EB hosts

---

benchmarks/utils.py
benchmarks/views/index.py

Hotfix to a bug where user does not see profile view models. This was due to some logic mismatch between submitter vs owner.
Also on cache invalidation, make sure user cache is cleared as well. Improved output to view preserved keys for debugging purpose.

Allow user/owner to view profile view
