brain-score/brain-score.web

- benchmarks/views/index.py
erroneously deleted in https://github.com/brain-score/brain-score.web/pull/42
> restore `no_children` and `no_benchmark` filters

- benchmarks/views/index.py
should prevent
```
File "/app/benchmarks/views/index.py", line 40, in get_context
model_rows = _collect_models(benchmarks, user)
File "/app/benchmarks/views/index.py", line 205, in _collect_models
np.nanmax(group['score_ceiled'])
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```
> filter for null scores to avoid errors in profile score display

- benchmarks/templates/benchmarks/table.html
- benchmarks/views/index.py
not sure if this is a good idea, I'm worried it will give the impression that engineering is factored into the average (#42 might make them look even more similar).
> only show brain benchmarks level 1, collapse engineering root

- web/settings.py
This is partly to address log errors we have been seeing like `KeyError: 'Incorrect'` (from [user.py](https://github.com/brain-score/brain-score.web/blob/6c67fbbbf8169b20b0130e1216fd1c9377bac820/benchmarks/views/user.py#L96) and [login.html](https://github.com/brain-score/brain-score.web/blob/6c67fbbbf8169b20b0130e1216fd1c9377bac820/benchmarks/templates/benchmarks/login.html#L31)) where the template checked for the variable with an `{% if %}` -- even though django [documentation states](https://docs.djangoproject.com/en/dev/ref/templates/builtins/#if) that it will also test for variable existence, it [apparently](https://github.com/golemfactory/concent/issues/626#issuecomment-404571208) still logs a DEBUG warning.
> set file log level to INFO if not debugging

- benchmarks/views/index.py
otherwise nan/null scores will fail with
```
File "/app/benchmarks/views/index.py", line 516, in format_score
return f"{score:.3f}"
TypeError: unsupported format string passed to NoneType.__format__
```
> catch all formatting errors for `format_score`

- benchmarks/templates/benchmarks/table.html
> display empty space instead of 'None' when display name is not set

- benchmarks/templates/benchmarks/model.html
erroneously removed in https://github.com/brain-score/brain-score.web/pull/119
before:
after:
> show paper reference link again for public models

- benchmarks/templates/benchmarks/model.html
- benchmarks/views/model.py
in other words, exclude private models from rank comparison.
before (notice how the rank is larger than the number of models that are publicly shown on the main leaderboard):
after:
resolve #155 @patrickmineault
> compute rank based on all public models

- benchmarks/views/user.py
This PR removes the `dev` part of `dev_run_benchmarks` and `dev_create_github_pr`.
> Hotfix: remove dev prefix from Jenkins job names

- benchmarks/urls.py
This PR sets the default URL for /profile to vision (in keeping with the other defaults for the site)
> Hotfix: default /profile link broken

- benchmarks/views/user.py
This PR:
1. Assigns the `score_plugin` job to language resubmissions
2. Builds a new language resubmission URL in line with `score_plugin's` parameter specifications
> Language resubmission job name/URL is fixed

- benchmarks/views/index.py
Fix via this: https://stackoverflow.com/questions/44522741/pandas-mean-typeerror-could-not-convert-to-numeric
Pandas 2.0 changed .mean() default parameter numeric_only to be False, when it was previously True.
> Hotfix: pandas 2.0 update

- benchmarks/templates/benchmarks/model.html
- benchmarks/views/index.py
This PR fixes this issue #180. This was caused when the `jenkins_id` was added and diverged from `submission_id`.
> Added jenkins_id to model meta to be used front end

- benchmarks/templates/benchmarks/competition.html
- benchmarks/templates/benchmarks/submissions.html
- benchmarks/tests/test_views.py
- benchmarks/views/competition.py
- benchmarks/views/index.py
Currently, for benchmarks with a lab identifier (e.g. `dicarlo.MajajHong2015.V4-pls`), a [benchmark short name is derived](https://github.com/brain-score/brain-score.web/blob/master/benchmarks/views/index.py#L210) by removing the lab identifier.
Since lab identifiers have been removed from benchmark identifiers in the database, the short name derivation now eliminates a part of the benchmark identifier instead (e.g. `MajajHong2015.V4-pls` -> `V4-pls`), causing display problems on the website (as highlighted in red below):
This PR fixes this by displaying the full benchmark identifier instead of the short name.
> Displaying benchmark identifier instead of short name on website

- benchmarks/views/user.py
This PR checks for spaces in files within zip submission, and outputs a specific error for users. Prior to this fix, plug-in only changes were wrongly flagged as non plug in changes because file names were being split by spaces. 
Closes issue #231
> add check for spaces in validate zip

- benchmarks/views/user.py
Previously, when submitting a model that has multiple DB entires (such as alexnet), the prod server would 500 due to the QueryFilter not returning multiple models. 
This fixes that by forcing the Query to return the first model it finds. So for multiple models, this only returns the first one, and for a single model, it will return itself. Should fix 500 error.
> Fixes duplicate model 500 error on submission

- benchmarks/views/user.py
Addresses issue [here](https://github.com/brain-score/vision/issues/714) in BSV. Also adds the user email to the URL in order for the email to be sent to the correct user on resubmission, modeling the [call](https://github.com/brain-score/brain-score.web/blob/1d2fc267ab8ad7600ce98d8b38d4f2975bc1042f/benchmarks/views/user.py#L223) to Jenkins in the Upload view.
> added user email and domain args to resubmit job links

- benchmarks/templates/benchmarks/tutorials/tutorial_troubleshooting.html
User reports indicate that `xarray` versioning can cause issues when running `model.py` in the tutorial. This adds the suggested fix to the troubleshooting page.
> Add Entry Points error to troubleshooting

- benchmarks/views/user.py
Some memory issues occurred while the limit was 5. During soft release the limit will be decreased to 1.
> limit plugins for soft release to 1

- benchmarks/views/user.py
Allow users to submit data and metric plugins.
Note: In the Zip parsing/validation logic, we look up the corresponding DB table for a plugin (`Model` for model plugins, `BenchmarkType` for benchmarks), but as there are no tables in the DB currently for metrics and data, this PR suggests we just use `BenchmarkType`, as it still checks against benchmark names (this is the closes relevant existing table to metrics and data).
> add support for data and metric plugins submission

- benchmarks/views/index.py
Previously, the compare tab used all models, instead of just public ones.
> remove private models from compare tab

- benchmarks/templates/benchmarks/competition2024.html
Very small update - change link from https://brain-score.readthedocs.io/en/latest/modules/benchmark_tutorial.html to https://www.brain-score.org/tutorials/benchmarks
> Minor update for full tutorial link

- benchmarks/templates/benchmarks/tutorials/models/quickstart.html
Added commands for installing Miniconda, and creating and activating a virtual conda environment.
Added a breakdown of the command line.  What the model and benchmark identifiers are, and gave examples that can be tried for swapping to new models and benchmarks.  Also put in links to the model and benchmark directories in the repo and explained how to find the model and benchmark identifiers for each model and benchmark.
Added a warning about how some models may have aggressive memory requirements for some machines.
Removed the link to the code about how the Majajhong benchmark is calculated, and instead described it in words.
Modified the time to run near the end.
> Jimn2 updating quickstart

- benchmarks/templates/benchmarks/base.html
- benchmarks/templates/benchmarks/leaderboard/info-section.html
- benchmarks/views/index.py
- static/benchmarks/js/download_csv.js
This PR adds a way to download the CSV data for model ceiled scores. It is cached and domain-independent, but is mostly a quick and dirty way to do this.
> Add Leaderboard CSV download

- benchmarks/templates/benchmarks/tutorials/models/deepdive_1.html
Was still missing the two `<div>` statements at L248 and L249 as well as the closing `</div>` at L260. Apologies ahead of time for the confusing Git diffs. Those three lines are essentially what was changed but also corrected code indenting for readability.
> Deep Dive 1 Sidebar and Image fix

- benchmarks/templates/benchmarks/leaderboard/leaderboard-table.html
Fixes an issue where the leaderboard sort was not working (most likely after we changed the names of benchmarks in the database).
> fix leaderboard sort

- benchmarks/templates/benchmarks/base.html
- benchmarks/templates/benchmarks/components/app-view.html
- benchmarks/templates/benchmarks/leaderboard/leaderboard.html
- static/benchmarks/css/components/info-section.sass
- static/benchmarks/css/components/left-sidebar.sass
- static/benchmarks/css/main.sass
- static/benchmarks/css/other.sass
- static/benchmarks/js/mobile_warning.js
> Mobile Site Styling  Hotfixes

- benchmarks/templates/benchmarks/leaderboard/legend.html
- benchmarks/views/index.py
- static/benchmarks/css/leaderboard/leaderboard-table.sass
- static/benchmarks/js/cache-status.js
"Nice to have" feature that displays when the leaderboard was last updated in the user's local time.
Might be useful for users who have submitted a model, that has been scored (indicated by the email), but hasn't shown up on the leaderboard yet.
> Add last updated status under leaderboard legend

- benchmarks/views/index.py
Scores are showing up in harsher colors than expected. The error comes from a stray `np . float` added into the opacity for each score chip, which stems from changes to the [float type](https://numpy.org/devdocs/release/2.2.0-notes.html#changes:~:text=The%20type%20annotations%20of%20numpy.float64%20and%20numpy.complex128%20now%20reflect%20that%20they%20are%20also%20subtypes%20of%20the%20built%2Din%20float%20and%20complex%20types%2C%20respectively.%20This%20update%20prevents%20static%20type%2Dcheckers%20from%20reporting%20errors%20in%20cases%20such%20as%3A) in the most recent version of numpy.
The easy fix is to cast to float. However, this does highlight that the deployed version of the website does not have pinned versions of libraries (unlike current localhost setups) as the docker …
> Fix for color issue on website

- web/settings.py
Changes the default database's URL from `brainscore-1-ohio-cred` to `brainscore-1-ohio-cred-migrated`. Note that this is the dev db, not prod or test. All three DBs were changed in the EB Configurator.
> Change default DB to use migrated DB

- benchmarks/fixtures/fixture-models-language.json
- benchmarks/fixtures/fixture-models.json
- benchmarks/fixtures/fixture-users-language.json
- benchmarks/fixtures/fixture-users.json
The original fixtures omitted the primary keys for each Django Model. Normally, when populating the fixtures in the test database, primary keys would be automatically assigned. 
However, while updating unit tests for #379, unit tests have not been able to run locally or on Jenkins when using `python manage.py test benchmarks -v 2 --no-input`. 
To address this, I added primary keys to avoid duplicate key errors and missing key errors. Unit tests are intact and now run locally and should run on Jenkins.
This is already part of #379 but feel it should be merged so that other PRs can pass/merge.
See http://www.brain-score-jenkins.com:8080/job/web/job/unittest_web/30/ for errors.
```
Traceback (most recent call last):
File "/home/ubuntu/miniconda3/envs/web_env/lib/python3.8/site-packages/django …
```
> Update fixtures to fix unit tests

- benchmarks/utils.py
- benchmarks/views/index.py
This is a small amendment to the Optimized Leaderboard Generation PR #379.
For some reason, dev and prod servers are not demonstrating the full performance gains seen locally across all developers. At first, @mike-ferguson and I thought this could be due to EB server hardware. However, upon a quick instance upgrade, the leaderboard was still taking ~10 seconds on second load instead of the ~1.5 seconds (after dictionary caching). This needs further exploration. 
As a temporary fix, I am re-introducing `@cache_page` HTML caching. I am also introducing a `cache.clear()` call in the `refresh_cache()` function. This now invalidates not only the dictionary cache but also the HTML cache upon materialized view refresh after scoring completion and rebuilds it appropriately. 
1. Visit leaderboard …
> Clear all cache on request

- benchmarks/templates/benchmarks/model.html
- benchmarks/views/model.py
Based on a previous change to leaderboard, model card per-benchmark ranking broke when logged in. This resulted in model cards (only after being logged in) to reflect per-benchmark ranks as 1 even if untrue. This has now been fixed with correct per-benchmark ranks.
Additionally, materialized view return submitter information in an incorrect format. This format was on display when viewing submitter information. I have chosen to remove the section entirely because much of the information is not useful or incompatible after the post-AWS migration.
> Fix model card information

- benchmarks/templates/benchmarks/leaderboard/ag-grid-leaderboard.html
- benchmarks/views/leaderboard.py
- static/benchmarks/css/leaderboard/ag-grid-leaderboard.sass
- static/benchmarks/js/ag-grid-leaderboard.js
Uses #398 as base.
- Update the leaderboard header to match previous leaderboard's aesthetic. 
- Made benchmark expand functionality triggered by "benchmark children" bubble. Added expand and collapse arrows like original leaderboard.
- Parent benchmark sort by triggered by full header. Child benchmark sort by triggered by sort by icon.
- Made AG-Grid's headers (i.e., rank, model, filtered score) sort by and custom headers (i.e., benchmark headers) sort by the same style for consistency. 
- Introduce benchmark card hyperlink to leaf benchmark headers
- Since parent benchmarks are abstract and do not have a benchmark card to link to, the entire header will trigger sort by functionality. Leaf benchmarks are actual benchmarks and therefore have a benchmark card to link to. As such, the …
> Update leaderboard overhaul header functionality and style

- static/benchmarks/css/leaderboard/ag-grid-leaderboard.sass
- static/benchmarks/js/ag-grid-leaderboard.js
Uses #398 as base.
Simple PR that adds the runnable metadata as a column called `Status`. If preferred, we can combine it with the model name column if a dedicated column is taking too much space.
Green status = model has been tested and runs
Red status = model has been tested and does not run
Gray status = model has not been tested so status unknown
https://github.com/user-attachments/assets/fb91521c-0af9-4e28-9fe0-0d3b34ed02df
> Add model runnable status icon to leaderboard

- benchmarks/templates/benchmarks/leaderboard/ag-grid-leaderboard.html
- benchmarks/views/leaderboard.py
- static/benchmarks/css/components/tooltip.sass
- static/benchmarks/css/leaderboard/ag-grid-leaderboard.sass
- static/benchmarks/js/ag-grid-leaderboard.js
- static/benchmarks/js/components/tooltip.js
Uses #398 as base.
Introduces a one-click citation list that is copy to clipboard based on current leaderboard view. Only supports benchmarks right now.
`copyBibtexToClipboard()` function added to `ag-grid-leaderboard.js`. Should be modularized in the future. 
1. Function calls `collectBenchmarkBibtex()` which collects the a set of filtered out (i.e., excluded) benchmarks and the benchmark hierarchy tree. 
2. We get the row data from the first model (assumes first model has no missing scores), and iterate over its benchmarks. 
3. Check if benchmark is a benchmark, has a bibtex, and is a leaf (i.e., no children). 
4. If it is, check if it is in the list of excludedBenchmarks (after some string parsing). 
5. If not in excludedBenchmarks, add to bibtexSet (captures only unique bibtex). 
6. …
> One-click citation list based on leaderboard view

- benchmarks/tests/test_views.py
- benchmarks/urls.py
- benchmarks/views/user.py
Addresses #440
Redirects to `/vision/{page}` by default unless on `/profile/{domain}` when then directs to `/{domain}/{page}`
> Hotfix: Fix broken nav bar links from /profile/

- benchmarks/templates/benchmarks/components/left-sidebar.html
- benchmarks/templates/benchmarks/leaderboard/ag-grid-leaderboard-content.html
- benchmarks/tests/test_views.py
- static/benchmarks/css/components/left-sidebar.sass
- static/benchmarks/css/leaderboard/components/_buttons.sass
- static/benchmarks/css/leaderboard/components/_filters.sass
- static/benchmarks/css/leaderboard/components/_range-sliders.sass
- static/benchmarks/css/leaderboard/layouts/_sidebar.sass
- static/benchmarks/js/leaderboard-tour.js
- static/benchmarks/js/leaderboard/issues/report-issue.js
Button is no longer red and cluttering space next to Advanced Filters. It has been converted to a text button and moved to the bottom left corner of the navigation bar. Additionally, it is now global wherever the nav bar is used.
Walkthrough/Tour button was large and dominating the space next to Advanced Filters. Have changed it to a small grey button and moved it to the right side. Less intrusive but same functionality
On certain browser dimensions, Advanced Filters in side bar mode would overflow out of the container. This has been fixed. Height adjustment of leaderboard to match sidebar not always instant and may require refresh but button overflow out of the container has been fixed.
> Fix leaderboard UI issues

- benchmarks/templates/benchmarks/leaderboard/ag-grid-leaderboard-content.html
- benchmarks/templates/benchmarks/leaderboard/ag-grid-leaderboard-shell.html
- benchmarks/templates/benchmarks/profile.html
Removed redundant references to main.css from profile and AG-Grid leaderboard templates that were causing 404 errors. The main CSS is already properly loaded through Django Compressor in the base template, which generates hashed CSS files.
This resolves console 404 errors that were interfering with Canary monitoring systems while maintaining all existing styling functionality.
> remove bad main.css calls

- benchmarks/templates/benchmarks/base.html
Unclear when the `kit.fontawesome/js` script broke but it no longer works. Returns forbidden.
Leaderboard Content page was loading FA icons through a different link, which works, but was conflicting with the `base.html` preventing them from being loaded globally. Have added the working link to `base.html`.
> Fix font awesome CSS loading
